routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'panel', 'namespace' => 'Admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/users', 'AdminController@index')->name('users');
        Route::get('/users/create', 'AdminController@create')->name('user.create');
        Route::post('/users/store', 'AdminController@store')->name('user.store');
        Route::get('/users/edit/{id}', 'AdminController@edit')->name('user.edit');
        Route::put('/users/update/{id}', 'AdminController@update')->name('user.update');
        Route::delete('/users/delete/{id}', 'AdminController@destroy')->name('user.destroy');

        Route::get('companies', 'CompanyController@index')->name('companies');
        Route::get('companies/create', 'CompanyController@create')->name('company.create');
        Route::post('companies/store', 'CompanyController@store')->name('company.store');
        Route::get('companies/edit/{id}', 'CompanyController@edit')->name('company.edit');
        Route::put('companies/update/{id}', 'CompanyController@update')->name('company.update');
        Route::delete('companies/delete/{id}', 'CompanyController@destroy')->name('company.destroy');

        Route::get('/forums', 'ForumController@index')->name('forums');
        Route::get('/forum/create', 'ForumController@create')->name('forum.create');
        Route::post('/forum/store', 'ForumController@store')->name('forum.store');
        Route::get('/forum/edit/{id}', 'ForumController@edit')->name('forum.edit');
        Route::put('/forum/uptate/{id}', 'ForumController@update')->name('forum.update');
        Route::get('forum/{id}/role-playing', 'RolePlayController@indexRolePlay')->name('forum.create.roleplay');
        Route::post('forum/store/role-playing', 'RolePlayController@storeRolePlay')->name('forum.store.roleplay');
        Route::get('forum/role-play/edit/hour/{id}', 'RolePlayController@edit');
        Route::delete('forum/role-play/delete/hour/{id}', 'RolePlayController@destroy');
        Route::post('forum/role-play/hour/update', 'RolePlayController@update');
        Route::get('forum/{id}/interview', 'InterviewController@indexInterview')->name('forum.create.interview');
        Route::post('forum/store/interview', 'InterviewController@storeInterview')->name('forum.store.interview');
        Route::get('forum/interview/edit/hour/{id}', 'InterviewController@edit');
        Route::delete('forum/interview/delete/hour/{id}', 'InterviewController@destroy');
        Route::post('forum/interview/hour/update', 'InterviewController@update');
        Route::get('forum/{id}/aula-tic', 'AulaTicController@indexAulaTic')->name('forum.create.aulatic');
        Route::post('forum/store/aula-tic', 'AulaTicController@storeAulaTic')->name('forum.store.aulatic');
        Route::get('forum/aula-tic/edit/{id}', 'AulaTicController@edit')->name('forum.edit.aulatic');
        Route::put('forum/aula-tic/update/{id}', 'AulaTicController@update')->name('forum.update.aulatic');
        Route::delete('forum/aula-tic/delete/{id}', 'AulaTicController@destroy');
        Route::get('forum/{id}/work-shops', 'WorkShopController@indexWorkShop')->name('forum.create.workshop');
        Route::post('forum/store/work-shops', 'WorkShopController@storeWorkShop')->name('forum.store.workshop');
        Route::get('forum/competitors', 'CompetitorController@index')->name('forum.competitors');
        Route::get('forum/competitors/data', 'CompetitorController@data')->name('forum.competitors.data');
        Route::get('forum/data', 'ForumController@data')->name('forums.data');
        Route::get('forum/competitor/add', 'CompetitorController@create')->name('forum.competitor.create');
        Route::post('forum/competitor/store', 'CompetitorController@store')->name('forum.competitor.store');
        Route::put('forum/status/active/', 'ForumController@active')->name('forum.status.active');
        Route::put('forum/status/disable/', 'ForumController@disable')->name('forum.status.disable');
        Route::delete('forum/delete/{id}', 'ForumController@destroy')->name('forum.destroy');

        Route::get('/charts/ages', 'ChartController@chartAges');

        Route::prefix('cities')->group(function () {
            Route::get('/', 'CityController@index')->name('cities');
            Route::get('/create', 'CityController@create')->name('city.create');
            Route::post('/store', 'CityController@store')->name('city.store');
            Route::get('/edit/{id}', 'CityController@edit')->name('city.edit');
            Route::put('/update/{id}', 'CityController@update')->name('city.update');
            Route::delete('/delete/{id}', 'CityController@destroy')->name('city.update');
        });

        Route::prefix('hours')->group(function () {
            Route::get('/', 'HourController@index')->name('hours');
            Route::get('/create', 'HourController@create')->name('hour.create');
            Route::post('/store', 'HourController@store')->name('hour.store');
            Route::get('/edit/{id}', 'HourController@edit')->name('hour.edit');
            Route::put('/update/{id}', 'HourController@update')->name('hour.update');
        });

        Route::prefix('events')->group(function () {
            Route::name('events.')->group(function (){
                Route::prefix('role-plays')->group(function () {
                    Route::get('/', 'RolePlayController@index')->name('roleplays');
                    Route::get('/data', 'RolePlayController@data')->name('rolpelay.data');
                });
                Route::prefix('interviews')->group(function () {
                    Route::get('/', 'InterviewController@index')->name('interviews');
                    Route::get('/data', 'InterviewController@data')->name('interview.data');
                });
                Route::prefix('aula-tics')->group(function () {
                    Route::get('/', 'AulaTicController@index')->name('aulatics');
                    Route::get('/data', 'AulaTicController@data')->name('aulatic.data');
                });
                Route::prefix('work-shops')->group(function () {
                    Route::get('/', 'WorkShopController@index')->name('workshops');
                    Route::get('/data', 'WorkShopController@data')->name('workshop.data');
                });
            });
        });
    });
});



Route::get('/', 'WebController@index')->name('forum');
Route::post('/competitor/store', 'WebController@storeCompetitor')->name('store.competitor');
Route::prefix('events')->group(function () {
    Route::get('role-playing/{id?}', 'WebController@rolePlaying')->name('web.role-playing');
    Route::post('store/roleplay', 'WebController@storeRolePlaying')->name('web.store.roleplay');
    Route::get('entrevistas/{id?}', 'WebController@interview')->name('web.interview');
    Route::post('store/interview', 'WebController@storeInterview')->name('web.store.interview');
    Route::get('aula-tic/{id?}', 'WebController@aulatic')->name('web.aulatic');
    Route::post('store/aula-tic', 'WebController@storeAulaTic')->name('web.store.aulatic');
    Route::get('workshop/{id?}', 'WebController@workshop')->name('web.workshop');
    Route::post('store/work-shop', 'WebController@storeWorkshop')->name('web.store.workshop');
});

Route::get('get/hours/forum', 'WebController@getHoursByForum')->name('roleplay.get.hours.forum');
Route::get('get/company/interview', 'WebController@getCompanyByInterview')->name('interview.get.company.forum');
Route::get('get/hours/interview', 'WebController@getHoursByInterview')->name('interview.get.hours.forum');
Route::get('get/curses/aula-tic', 'WebController@getCursesByForum')->name('aulatic.get.curses.forum');
Route::get('get/workshops', 'WebController@getWorkShops')->name('forum.get.workshop');

Route::get('lang/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/Http/Controllers/Admin/ForumController.php
<?php

namespace App\Http\Controllers\Admin;

use App\City;
use App\Forum;
use App\Http\Controllers\Controller;
use App\Http\Requests\ForumStoreRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;
use Yajra\DataTables\DataTables;

class ForumController extends Controller
{

    public function index()
    {
        $pageTitle = 'Foros';
        $pageIcon = 'fas fa-home';
        $forums = Forum::all();

        return view('cpanel.forums.index', compact('pageIcon', 'pageTitle', 'forums'));
    }

    public function create()
    {
        $pageTitle = 'Nuevo Foro';
        $pageIcon = 'fas fa-plus';
        $cities = City::Active()->get();
        return view('cpanel.forums.create', compact('pageTitle', 'pageIcon', 'cities'));
    }

    public function store(ForumStoreRequest $request)
    {
        $forum = new Forum($request->except('program_es', 'program_ca'));
        if ($request->hasFile('program_es')) {
            $file = $request->file('program_es');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/es/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_es')->move($destination_path,$filename);

            $forum->program_es = $filename;
        }
        if ($request->hasFile('program_ca')) {
            $file = $request->file('program_ca');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/ca/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_ca')->move($destination_path,$filename);

            $forum->program_ca = $filename;
        }
        $forum->save();

        toastSuccess('Forum creado');
        return Redirect::route('admin.forums');
    }

    public function edit($id)
    {
        $pageTitle = 'Editar Forum';
        $pageIcon = 'fas fa-edit';
        $cities = City::Active()->get();
        $forum = Forum::find($id);

        return view('cpanel.forums.edit', compact('pageIcon', 'pageTitle', 'forum', 'cities'));
    }

    public function update(Request $request, $id)
    {
        $forum = Forum::find($id);
        if ($request->hasFile('program_es')) {
            File::delete(public_path() . '/uploads/docs/es/' . $forum->program_es);
            $file = $request->file('program_es');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/es/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_es')->move($destination_path,$filename);

            $forum->program_es = $filename;
        }
        if ($request->hasFile('program_ca')) {
            File::delete(public_path() . '/uploads/docs/ca/' . $forum->program_ca);
            $file = $request->file('program_ca');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/ca/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_ca')->move($destination_path,$filename);

            $forum->program_ca = $filename;
        };
        $forum->update($request->except('program_es', 'program_ca'));

        toastSuccess('Forum actualizado.');
        return Redirect::route('admin.forums');
    }

    public function data()
    {
        $forums = Forum::all();

        return DataTables::of($forums)
            ->editColumn('created_at', function (Forum $forum) {
                return $forum->created_at;
            })
            ->editColumn('date', function(Forum $forum) {
                return $forum->date->format('dM');
            })
            ->editColumn('city', function (Forum $forum) {
                return $forum->city->getCity();
            })
            ->editColumn('location', function (Forum $forum) {
                return $forum->getLocation();
            })
            ->addColumn('actions', function ($forum) {
                $action = '';
                $action .= '<a title="Editar Foro" href="'.route('admin.forum.edit', $forum->id).'" class="btn btn-info-soft btn-sm mr-1"><i class="far fa-edit"></i></a>';
                $action .= '<a title="Asignar Role Play" href="'.route('admin.forum.create.roleplay', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="far fa-clipboard"></i></a>';
                $action .= '<a title="Asignar Entrevistas" href="'.route('admin.forum.create.interview', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="fas fa-pen-alt"></i></a>';
                $action .= '<a title="Asignar Aula TIC" href="'.route('admin.forum.create.aulatic', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="fas fa-bullhorn"></i></a>';
                $action .= '<a title="Asignar Work Shop" href="'.route('admin.forum.create.workshop', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="fas fa-toolbox"></i></a>';
//                $action .= '<a href="#" onclick="deleteForum('.$forum->id.')" class="btn btn-danger-soft btn-sm "><i class="fas fa-trash"></i></a>';
                $action .= '<a href="#" class="btn btn-danger-soft btn-sm "><i class="fas fa-trash"></i></a>';
                if ($forum->status == true){
//                    $action .= '<a href="#" onclick="disableForum('.$forum->id.')" class="btn btn-danger-soft btn-sm "><i class="fas fa-ban"></i></a>';
                    $action .= '<a href="#" class="btn btn-danger-soft btn-sm "><i class="fas fa-ban"></i></a>';
                }else{
//                    $action .= '<a href="#" onclick="activeForum('.$forum->id.')" class="btn btn-success-soft btn-sm "><i class="fas fa-check-circle"></i></a>';
                    $action .= '<a href="#" class="btn btn-success-soft btn-sm "><i class="fas fa-check-circle"></i></a>';
                }
//                $action .= '<a href="#" onclick="deleteForum('.$forum->id.')" class="btn btn-danger-soft btn-sm "><i class="fas fa-trash"></i></a>';
                return $action;
            })
            ->rawColumns(['actions', 'city', 'location'])
            ->make(true);
    }

    public function destroy(Request $request)
    {
        $data = [];
        $data['success'] = false;

        $id = $request->id;
        $forum  = Forum::find($id);
        if (empty($forum)){
            $data['message'] = 'Error al eliminar este Foro';
            return $this->ReturnJson($data);
        }
        $forum->delete();

        $data['success'] = true;
        $data['message'] = 'Foro Eliminado';
        return $this->ReturnJson($data);
    }

    public function active(Request $request)
    {
        $data = [];
        $data['success'] = false;

        $id = $request->id;
        $forum  = Forum::find($id);
        if (empty($forum)){
            $data['message'] = 'Error al activar este Foro';
            return $this->ReturnJson($data);
        }
        $forum->status = 1;
        $forum->save();

        $data['success'] = true;
        $data['message'] = 'Foro Activado';
        return $this->ReturnJson($data);
    }

    public function disable(Request $request)
    {
        $data = [];
        $data['success'] = false;

        $id = $request->id;
        $forum  = Forum::find($id);
        if (empty($forum)){
            $data['message'] = 'Error al deshabilitar este Foro';
            return $this->ReturnJson($data);
        }
        $forum->status = 0;
        $forum->save();

        $data['success'] = true;
        $data['message'] = 'Foro deshabilitado';
        return $this->ReturnJson($data);
    }
}

resources/views/cpanel/forums/lists/forum_aulas.blade.php
<div class="row mt-2">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Lista de cursos</h6>
                    </div>
                    <div class="text-right">
                        <div class="actions">
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-stripe table-hover">
                    <thead>
                    <tr>
                        <th>Nombre Curso ES</th>
                        <th>Nombre Curso VAL</th>
                        <th>Hora</th>
                        <th>Plazas</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($aula_tics as $key => $aula)
                    <tr id="aula_id_{{$aula->id}}">
                        <td>{{$aula->curse_es}}</td>
                        <td>{{$aula->curse_ca}}</td>
                        <td>{{$aula->hour}}</td>
                        <td>{{$aula->places}}</td>
                        <td>
                            <a href="#" class="btn btn-info-soft btn-sm"><i class="fas fa-edit"></i></a>
{{--                            <a href="{{route('admin.forum.edit.aulatic', $aula->id)}}" class="btn btn-info-soft btn-sm"><i class="fas fa-edit"></i></a>--}}
{{--                            <a href="#" onclick="deleteAulatic({{$aula->id}})" class="btn btn-danger-soft btn-sm"><i class="fas fa-trash"></i></a>--}}
                            <a href="#" class="btn btn-danger-soft btn-sm"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

resources/views/cpanel/forums/lists/forum_interview.blade.php
    <div class="col-md-7">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Horas</h6>
                    </div>
                    <div class="text-right">
                        <div class="actions">

                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <div class="table-responsive">
                    <table class="table table-stripe table-hover">
                        <thead>
                            <tr>
                                <th>Empresa</th>
                                <th>Horas</th>
                                <th>Plazas</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($interviews as $key => $hour)
                            <tr id="interview_id_{{ $hour->id }}">
                                <td>{{$hour->company->name}}</td>
                                <td>
                                    @foreach($hour->company_hour_interview as $hour)
                                        {{$hour->getHour()}}<br>
                                    @endforeach
                                </td>
                                <td>{{$hour->places}}</td>
                                <td>
{{--                                    <a href="javascript:void(0)" id="edit-interview" data-id="{{ $hour->id }}" class="btn btn-info-soft btn-sm mr-2"><i class="fas fa-edit"></i></a>--}}
                                    <a href="#" id="edit-interview"  class="btn btn-info-soft btn-sm mr-2"><i class="fas fa-edit"></i></a>
{{--                                    <a href="javascript:void(0)" id="delete-interview" data-id="{{ $hour->id }}" class="btn btn-danger-soft btn-sm"><i class="fas fa-trash"></i></a>--}}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

resources/views/cpanel/forums/lists/forum_role_play.blade.php
    <div class="col-md-7">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Horas</h6>
                    </div>
                    <div class="text-right">
                        <div class="actions">

                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <div class="table-responsive">
                    <table class="table table-stripe table-hover">
                        <thead>
                            <tr>
                                <th>Hora</th>
                                <th>Plazas</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($roleplays as $key => $hour)
                            <tr id="roleplay_id_{{ $hour->id }}">
                                <td>{{$hour->hour}}</td>
                                <td>{{$hour->places}}</td>
                                <td>
                                    <a href="#"  class="btn btn-info-soft btn-sm mr-2"><i class="fas fa-edit"></i></a>
{{--                                    <a href="javascript:void(0)" id="edit-roleplay" data-id="{{ $hour->id }}" class="btn btn-info-soft btn-sm mr-2"><i class="fas fa-edit"></i></a>--}}
{{--                                    <a href="javascript:void(0)" id="delete-roleplay" data-id="{{ $hour->id }}" class="btn btn-danger-soft btn-sm"><i class="fas fa-trash"></i></a>--}}
                                    <a href="#"  class="btn btn-danger-soft btn-sm"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

resources/views/cpanel/forums/lists/forum_workshops.blade.php
<div class="row mt-3">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fs-17 font-weight-600 mb-0">Work Shops</h6>
                    </div>
                    <div class="text-right">
                        <div class="actions">

                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <div class="table-responsive">
                    <table class="table table-stripe table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Temario ES</th>
                                <th>Temario VAL</th>
                                <th>Hora</th>
                                <th>Plazas</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($workshops as $key => $workshop)
                            <tr>
                                <td>{{$workshop->position}}</td>
                                <td>{{$workshop->temary_es}}</td>
                                <td>{{$workshop->temary_ca}}</td>
                                <td>{{$workshop->hour}}</td>
                                <td>{{$workshop->places}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>