routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'panel', 'namespace' => 'Admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/users', 'AdminController@index')->name('users');
        Route::get('/users/create', 'AdminController@create')->name('user.create');
        Route::post('/users/store', 'AdminController@store')->name('user.store');
        Route::get('/users/edit/{id}', 'AdminController@edit')->name('user.edit');
        Route::put('/users/update/{id}', 'AdminController@update')->name('user.update');
        Route::delete('/users/delete/{id}', 'AdminController@destroy')->name('user.destroy');

        Route::get('companies', 'CompanyController@index')->name('companies');
        Route::get('companies/create', 'CompanyController@create')->name('company.create');
        Route::post('companies/store', 'CompanyController@store')->name('company.store');
        Route::get('companies/edit/{id}', 'CompanyController@edit')->name('company.edit');
        Route::put('companies/update/{id}', 'CompanyController@update')->name('company.update');
        Route::delete('companies/delete/{id}', 'CompanyController@destroy')->name('company.destroy');

        Route::get('/forums', 'ForumController@index')->name('forums');
        Route::get('/forum/create', 'ForumController@create')->name('forum.create');
        Route::post('/forum/store', 'ForumController@store')->name('forum.store');
        Route::get('/forum/edit/{id}', 'ForumController@edit')->name('forum.edit');
        Route::put('/forum/uptate/{id}', 'ForumController@update')->name('forum.update');
        Route::get('forum/{id}/role-playing', 'RolePlayController@indexRolePlay')->name('forum.create.roleplay');
        Route::post('forum/store/role-playing', 'RolePlayController@storeRolePlay')->name('forum.store.roleplay');
        Route::get('forum/role-play/edit/hour/{id}', 'RolePlayController@edit');
        Route::delete('forum/role-play/delete/hour/{id}', 'RolePlayController@destroy');
        Route::post('forum/role-play/hour/update', 'RolePlayController@update');
        Route::get('forum/{id}/interview', 'InterviewController@indexInterview')->name('forum.create.interview');
        Route::post('forum/store/interview', 'InterviewController@storeInterview')->name('forum.store.interview');
        Route::get('forum/interview/edit/hour/{id}', 'InterviewController@edit');
        Route::delete('forum/interview/delete/hour/{id}', 'InterviewController@destroy');
        Route::post('forum/interview/hour/update', 'InterviewController@update');
        Route::get('forum/{id}/aula-tic', 'AulaTicController@indexAulaTic')->name('forum.create.aulatic');
        Route::post('forum/store/aula-tic', 'AulaTicController@storeAulaTic')->name('forum.store.aulatic');
        Route::get('forum/aula-tic/edit/{id}', 'AulaTicController@edit')->name('forum.edit.aulatic');
        Route::put('forum/aula-tic/update/{id}', 'AulaTicController@update')->name('forum.update.aulatic');
        Route::delete('forum/aula-tic/delete/{id}', 'AulaTicController@destroy');
        Route::get('forum/{id}/work-shops', 'WorkShopController@indexWorkShop')->name('forum.create.workshop');
        Route::post('forum/store/work-shops', 'WorkShopController@storeWorkShop')->name('forum.store.workshop');
        Route::get('forum/competitors', 'CompetitorController@index')->name('forum.competitors');
        Route::get('forum/competitors/data', 'CompetitorController@data')->name('forum.competitors.data');
        Route::get('forum/data', 'ForumController@data')->name('forums.data');
        Route::get('forum/competitor/add', 'CompetitorController@create')->name('forum.competitor.create');
        Route::post('forum/competitor/store', 'CompetitorController@store')->name('forum.competitor.store');
        Route::put('forum/status/active/', 'ForumController@active')->name('forum.status.active');
        Route::put('forum/status/disable/', 'ForumController@disable')->name('forum.status.disable');
        Route::delete('forum/delete/{id}', 'ForumController@destroy')->name('forum.destroy');

        Route::get('/charts/ages', 'ChartController@chartAges');

        Route::prefix('cities')->group(function () {
            Route::get('/', 'CityController@index')->name('cities');
            Route::get('/create', 'CityController@create')->name('city.create');
            Route::post('/store', 'CityController@store')->name('city.store');
            Route::get('/edit/{id}', 'CityController@edit')->name('city.edit');
            Route::put('/update/{id}', 'CityController@update')->name('city.update');
            Route::delete('/delete/{id}', 'CityController@destroy')->name('city.update');
        });

        Route::prefix('hours')->group(function () {
            Route::get('/', 'HourController@index')->name('hours');
            Route::get('/create', 'HourController@create')->name('hour.create');
            Route::post('/store', 'HourController@store')->name('hour.store');
            Route::get('/edit/{id}', 'HourController@edit')->name('hour.edit');
            Route::put('/update/{id}', 'HourController@update')->name('hour.update');
        });

        Route::prefix('events')->group(function () {
            Route::name('events.')->group(function (){
                Route::prefix('role-plays')->group(function () {
                    Route::get('/', 'RolePlayController@index')->name('roleplays');
                    Route::get('/data', 'RolePlayController@data')->name('rolpelay.data');
                });
                Route::prefix('interviews')->group(function () {
                    Route::get('/', 'InterviewController@index')->name('interviews');
                    Route::get('/data', 'InterviewController@data')->name('interview.data');
                });
                Route::prefix('aula-tics')->group(function () {
                    Route::get('/', 'AulaTicController@index')->name('aulatics');
                    Route::get('/data', 'AulaTicController@data')->name('aulatic.data');
                });
                Route::prefix('work-shops')->group(function () {
                    Route::get('/', 'WorkShopController@index')->name('workshops');
                    Route::get('/data', 'WorkShopController@data')->name('workshop.data');
                });
            });
        });
    });
});



Route::get('/', 'WebController@index')->name('forum');
Route::post('/competitor/store', 'WebController@storeCompetitor')->name('store.competitor');
Route::prefix('events')->group(function () {
    Route::get('role-playing/{id?}', 'WebController@rolePlaying')->name('web.role-playing');
    Route::post('store/roleplay', 'WebController@storeRolePlaying')->name('web.store.roleplay');
    Route::get('entrevistas/{id?}', 'WebController@interview')->name('web.interview');
    Route::post('store/interview', 'WebController@storeInterview')->name('web.store.interview');
    Route::get('aula-tic/{id?}', 'WebController@aulatic')->name('web.aulatic');
    Route::post('store/aula-tic', 'WebController@storeAulaTic')->name('web.store.aulatic');
    Route::get('workshop/{id?}', 'WebController@workshop')->name('web.workshop');
    Route::post('store/work-shop', 'WebController@storeWorkshop')->name('web.store.workshop');
});

Route::get('get/hours/forum', 'WebController@getHoursByForum')->name('roleplay.get.hours.forum');
Route::get('get/company/interview', 'WebController@getCompanyByInterview')->name('interview.get.company.forum');
Route::get('get/hours/interview', 'WebController@getHoursByInterview')->name('interview.get.hours.forum');
Route::get('get/curses/aula-tic', 'WebController@getCursesByForum')->name('aulatic.get.curses.forum');
Route::get('get/workshops', 'WebController@getWorkShops')->name('forum.get.workshop');

Route::get('lang/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/Http/Controllers/Admin/CompetitorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\ForumRegistered;
use App\Forum;
use App\ForumCompetitor;
use App\Http\Controllers\Controller;
use App\Http\Requests\CompetitorStoreRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Yajra\DataTables\Facades\DataTables;

class CompetitorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pageTitle = 'Participantes';
        $pageIcon = 'fas fa-users';
        $forums = Forum::all();
        $competitors = ForumCompetitor::all();

        return view('cpanel.competitors.index', compact(
            'competitors', 'pageTitle', 'pageIcon', 'forums'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pageTitle = 'Asignar Participante';
        $pageIcon = 'fas fa-user';
        $forums = Forum::all();

        return view('cpanel.competitors.create', compact(
            'pageTitle', 'pageIcon', 'forums'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CompetitorStoreRequest $request)
    {
        $competitor = new ForumCompetitor($request->except(['code']));
        $competitor->code = generateCodeNumber();
        $competitor->save();

        event(new ForumRegistered($competitor));
        toastSuccess('Participante agregado al Foro.');
        return Redirect::route('admin.forum.competitors');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function data(Request $request)
    {


        if ($request->forum != 'all')
        {
            $forums = ForumCompetitor::where('forum_id', $request->forum)->get();
        }else{
            $forums = ForumCompetitor::all();
        }

        return DataTables::of($forums)
            ->editColumn('code', function (ForumCompetitor $forum) {
                return $forum->code;
            })
            ->editColumn('genre', function (ForumCompetitor $forum) {
                return $forum->getGenre();
            })
            ->editColumn('forum', function ($forum){
                return $forum->forum->city->getCity();
            })
            ->rawColumns(['code', 'forum', 'genre'])
            ->make(true);

    }

}

resources/views/cpanel/competitors/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="fs-17 font-weight-600 mb-0">Nuevo Foro</h6>
                        </div>
                        <div class="text-right">
                            <div class="actions">
                                <a href="{{route('admin.forums')}}" class="btn btn-inverse btn-sm">
                                    Atras
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    @endif
                    <form action="{{route('admin.forum.competitor.store')}}" method="POST" id="competitor-create" class="form-group">
                        @csrf
                        <div class="form-row mb-2">
                            <div class="col-md-4">
                                <label for="forum" class="font-weight-600">Foro</label>
                                <select name="forum_id" id="forum" class="form-control" required>
                                    <option value="">Seleccioanr Foro</option>
                                    @foreach($forums as $forum)
                                        <option value="{{$forum->id}}">{{$forum->city->getCity()}}</option>
                                        @endforeach
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label for="first_name" class="font-weight-600">Nombre</label>
                                <input type="text" class="form-control" name="first_name" id="first_name" value="{{old('first_name')}}" placeholder="Nombre Participante" required>
                            </div>
                            <div class="col-md-4">
                                <label for="last_name" class="font-weight-600">Apellidos</label>
                                <input type="text" class="form-control" name="last_name" id="last_name" value="{{old('last_name')}}" placeholder="Apellidos del Participante" required>
                            </div>
                        </div>
                        <div class="form-row mb-3">
                            <div class="col-md-4">
                                <label for="dni" class="font-weight-600">DNI</label>
                                <input type="text" class="form-control" name="dni" id="first_name" value="{{old('dni')}}" placeholder="Numero de Identificación" required>
                            </div>
                            <div class="col-md-4">
                                <label for="email" class="font-weight-600">Correo</label>
                                <input type="email" class="form-control" name="email" id="email" value="{{old('email')}}" placeholder="Correo Electrónico" required>
                            </div>
                            <div class="col-md-4">
                                <label for="phone" class="font-weight-600">Telefono</label>
                                <input type="text" class="form-control" name="phone" id="phone" value="{{old('phone')}}" placeholder="Telefono Participante" required>
                            </div>

                        </div>
                        <button type="submit" class="btn btn-success ml-2">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cpanel/competitors/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="fs-17 font-weight-600 mb-0">Participantes</h6>
                        </div>
                        <div class="text-right">
                            <div class="actions">
                                <a href="{{route('admin.forum.competitor.create')}}" class="btn btn-success btn-sm">Nuevo</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <div class="form-inline" action="">
                                <label for="forum" class="mr-2">Foro</label>
                                <select class="form-control col-md-2 mb-2 mr-sm-2" name="forum" id="forum">
                                    <option value="all">Todos</option>
                                    @foreach($forums as $forum)
                                        <option value="{{$forum->id}}">{{$forum->forum_info}}</option>
                                    @endforeach
                                </select>
                                <button type="submit" class="btn btn-success mb-2" id="filter">Filtrar</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table display table-bordered table-striped table-hover" id="competitors-table">
                                    <thead>
                                    <tr>
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>DNI</th>
                                        <th>Edad</th>
                                        <th>Genero</th>
                                        <th>Correo</th>
                                        <th>Foro</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $(document).ready(function(){

            fill_datatable();

            function fill_datatable(forum = 'all')
            {
                var dataTable = $('#competitors-table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax:{
                        url: "{{ route('admin.forum.competitors.data') }}?forum=" + forum,
                        // data:{forum:forum}
                    },
                    columns: [
                        {
                            data:'code',
                            name:'code'
                        },
                        {
                            data:'first_name',
                            name:'first_name'
                        },
                        {
                            data:'last_name',
                            name:'last_name'
                        },
                        {
                            data:'dni',
                            name:'dni'
                        },
                        {
                            data:'age',
                            name:'age'
                        },
                        {
                            data:'genre',
                            name:'genre'
                        },
                        {
                            data:'email',
                            name:'email'
                        },
                        {
                            data:'forum',
                            name:'forum'
                        }
                    ],

                });
                new $.fn.dataTable.Buttons( dataTable, {
                    buttons: [
                        {
                            extend: 'excel',
                            className: 'btn-success mb-3',
                        },
                        {
                            extend: 'print',
                            className: 'btn-success mb-3'
                        },
                        {
                            extend: 'csv',
                            className: 'btn-success mb-3'
                        }
                    ]
                } );

                dataTable.buttons( 0, null ).container().prependTo(
                    dataTable.table().container()
                );
            }


            $('#filter').click(function(){
                var forum = $('#forum').val();

                if(forum !== '')
                {
                    $('#competitors-table').DataTable().destroy();
                    fill_datatable(forum);
                    $('#export')
                }
            });



        });
    </script>
    @endpush