routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'panel', 'namespace' => 'Admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/users', 'AdminController@index')->name('users');
        Route::get('/users/create', 'AdminController@create')->name('user.create');
        Route::post('/users/store', 'AdminController@store')->name('user.store');
        Route::get('/users/edit/{id}', 'AdminController@edit')->name('user.edit');
        Route::put('/users/update/{id}', 'AdminController@update')->name('user.update');
        Route::delete('/users/delete/{id}', 'AdminController@destroy')->name('user.destroy');

        Route::get('companies', 'CompanyController@index')->name('companies');
        Route::get('companies/create', 'CompanyController@create')->name('company.create');
        Route::post('companies/store', 'CompanyController@store')->name('company.store');
        Route::get('companies/edit/{id}', 'CompanyController@edit')->name('company.edit');
        Route::put('companies/update/{id}', 'CompanyController@update')->name('company.update');
        Route::delete('companies/delete/{id}', 'CompanyController@destroy')->name('company.destroy');

        Route::get('/forums', 'ForumController@index')->name('forums');
        Route::get('/forum/create', 'ForumController@create')->name('forum.create');
        Route::post('/forum/store', 'ForumController@store')->name('forum.store');
        Route::get('/forum/edit/{id}', 'ForumController@edit')->name('forum.edit');
        Route::put('/forum/uptate/{id}', 'ForumController@update')->name('forum.update');
        Route::get('forum/{id}/role-playing', 'RolePlayController@indexRolePlay')->name('forum.create.roleplay');
        Route::post('forum/store/role-playing', 'RolePlayController@storeRolePlay')->name('forum.store.roleplay');
        Route::get('forum/role-play/edit/hour/{id}', 'RolePlayController@edit');
        Route::delete('forum/role-play/delete/hour/{id}', 'RolePlayController@destroy');
        Route::post('forum/role-play/hour/update', 'RolePlayController@update');
        Route::get('forum/{id}/interview', 'InterviewController@indexInterview')->name('forum.create.interview');
        Route::post('forum/store/interview', 'InterviewController@storeInterview')->name('forum.store.interview');
        Route::get('forum/interview/edit/hour/{id}', 'InterviewController@edit');
        Route::delete('forum/interview/delete/hour/{id}', 'InterviewController@destroy');
        Route::post('forum/interview/hour/update', 'InterviewController@update');
        Route::get('forum/{id}/aula-tic', 'AulaTicController@indexAulaTic')->name('forum.create.aulatic');
        Route::post('forum/store/aula-tic', 'AulaTicController@storeAulaTic')->name('forum.store.aulatic');
        Route::get('forum/aula-tic/edit/{id}', 'AulaTicController@edit')->name('forum.edit.aulatic');
        Route::put('forum/aula-tic/update/{id}', 'AulaTicController@update')->name('forum.update.aulatic');
        Route::delete('forum/aula-tic/delete/{id}', 'AulaTicController@destroy');
        Route::get('forum/{id}/work-shops', 'WorkShopController@indexWorkShop')->name('forum.create.workshop');
        Route::post('forum/store/work-shops', 'WorkShopController@storeWorkShop')->name('forum.store.workshop');
        Route::get('forum/competitors', 'CompetitorController@index')->name('forum.competitors');
        Route::get('forum/competitors/data', 'CompetitorController@data')->name('forum.competitors.data');
        Route::get('forum/data', 'ForumController@data')->name('forums.data');
        Route::get('forum/competitor/add', 'CompetitorController@create')->name('forum.competitor.create');
        Route::post('forum/competitor/store', 'CompetitorController@store')->name('forum.competitor.store');
        Route::put('forum/status/active/', 'ForumController@active')->name('forum.status.active');
        Route::put('forum/status/disable/', 'ForumController@disable')->name('forum.status.disable');
        Route::delete('forum/delete/{id}', 'ForumController@destroy')->name('forum.destroy');

        Route::get('/charts/ages', 'ChartController@chartAges');

        Route::prefix('cities')->group(function () {
            Route::get('/', 'CityController@index')->name('cities');
            Route::get('/create', 'CityController@create')->name('city.create');
            Route::post('/store', 'CityController@store')->name('city.store');
            Route::get('/edit/{id}', 'CityController@edit')->name('city.edit');
            Route::put('/update/{id}', 'CityController@update')->name('city.update');
            Route::delete('/delete/{id}', 'CityController@destroy')->name('city.update');
        });

        Route::prefix('hours')->group(function () {
            Route::get('/', 'HourController@index')->name('hours');
            Route::get('/create', 'HourController@create')->name('hour.create');
            Route::post('/store', 'HourController@store')->name('hour.store');
            Route::get('/edit/{id}', 'HourController@edit')->name('hour.edit');
            Route::put('/update/{id}', 'HourController@update')->name('hour.update');
        });

        Route::prefix('events')->group(function () {
            Route::name('events.')->group(function (){
                Route::prefix('role-plays')->group(function () {
                    Route::get('/', 'RolePlayController@index')->name('roleplays');
                    Route::get('/data', 'RolePlayController@data')->name('rolpelay.data');
                });
                Route::prefix('interviews')->group(function () {
                    Route::get('/', 'InterviewController@index')->name('interviews');
                    Route::get('/data', 'InterviewController@data')->name('interview.data');
                });
                Route::prefix('aula-tics')->group(function () {
                    Route::get('/', 'AulaTicController@index')->name('aulatics');
                    Route::get('/data', 'AulaTicController@data')->name('aulatic.data');
                });
                Route::prefix('work-shops')->group(function () {
                    Route::get('/', 'WorkShopController@index')->name('workshops');
                    Route::get('/data', 'WorkShopController@data')->name('workshop.data');
                });
            });
        });
    });
});



Route::get('/', 'WebController@index')->name('forum');
Route::post('/competitor/store', 'WebController@storeCompetitor')->name('store.competitor');
Route::prefix('events')->group(function () {
    Route::get('role-playing/{id?}', 'WebController@rolePlaying')->name('web.role-playing');
    Route::post('store/roleplay', 'WebController@storeRolePlaying')->name('web.store.roleplay');
    Route::get('entrevistas/{id?}', 'WebController@interview')->name('web.interview');
    Route::post('store/interview', 'WebController@storeInterview')->name('web.store.interview');
    Route::get('aula-tic/{id?}', 'WebController@aulatic')->name('web.aulatic');
    Route::post('store/aula-tic', 'WebController@storeAulaTic')->name('web.store.aulatic');
    Route::get('workshop/{id?}', 'WebController@workshop')->name('web.workshop');
    Route::post('store/work-shop', 'WebController@storeWorkshop')->name('web.store.workshop');
});

Route::get('get/hours/forum', 'WebController@getHoursByForum')->name('roleplay.get.hours.forum');
Route::get('get/company/interview', 'WebController@getCompanyByInterview')->name('interview.get.company.forum');
Route::get('get/hours/interview', 'WebController@getHoursByInterview')->name('interview.get.hours.forum');
Route::get('get/curses/aula-tic', 'WebController@getCursesByForum')->name('aulatic.get.curses.forum');
Route::get('get/workshops', 'WebController@getWorkShops')->name('forum.get.workshop');

Route::get('lang/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/Http/Controllers/Admin/ForumController.php
<?php

namespace App\Http\Controllers\Admin;

use App\City;
use App\Forum;
use App\Http\Controllers\Controller;
use App\Http\Requests\ForumStoreRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;
use Yajra\DataTables\DataTables;

class ForumController extends Controller
{

    public function index()
    {
        $pageTitle = 'Foros';
        $pageIcon = 'fas fa-home';
        $forums = Forum::all();

        return view('cpanel.forums.index', compact('pageIcon', 'pageTitle', 'forums'));
    }

    public function create()
    {
        $pageTitle = 'Nuevo Foro';
        $pageIcon = 'fas fa-plus';
        $cities = City::Active()->get();
        return view('cpanel.forums.create', compact('pageTitle', 'pageIcon', 'cities'));
    }

    public function store(ForumStoreRequest $request)
    {
        $forum = new Forum($request->except('program_es', 'program_ca'));
        if ($request->hasFile('program_es')) {
            $file = $request->file('program_es');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/es/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_es')->move($destination_path,$filename);

            $forum->program_es = $filename;
        }
        if ($request->hasFile('program_ca')) {
            $file = $request->file('program_ca');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/ca/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_ca')->move($destination_path,$filename);

            $forum->program_ca = $filename;
        }
        $forum->save();

        toastSuccess('Forum creado');
        return Redirect::route('admin.forums');
    }

    public function edit($id)
    {
        $pageTitle = 'Editar Forum';
        $pageIcon = 'fas fa-edit';
        $cities = City::Active()->get();
        $forum = Forum::find($id);

        return view('cpanel.forums.edit', compact('pageIcon', 'pageTitle', 'forum', 'cities'));
    }

    public function update(Request $request, $id)
    {
        $forum = Forum::find($id);
        if ($request->hasFile('program_es')) {
            File::delete(public_path() . '/uploads/docs/es/' . $forum->program_es);
            $file = $request->file('program_es');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/es/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_es')->move($destination_path,$filename);

            $forum->program_es = $filename;
        }
        if ($request->hasFile('program_ca')) {
            File::delete(public_path() . '/uploads/docs/ca/' . $forum->program_ca);
            $file = $request->file('program_ca');
            $file_extension = $file->getClientOriginalExtension();
            $random_name = Str::slug($file->getClientOriginalName()) . '-' . time();
            $destination_path = public_path().'/uploads/docs/ca/';
            $filename = $random_name.'.'.$file_extension;
            $request->file('program_ca')->move($destination_path,$filename);

            $forum->program_ca = $filename;
        };
        $forum->update($request->except('program_es', 'program_ca'));

        toastSuccess('Forum actualizado.');
        return Redirect::route('admin.forums');
    }

    public function data()
    {
        $forums = Forum::all();

        return DataTables::of($forums)
            ->editColumn('created_at', function (Forum $forum) {
                return $forum->created_at;
            })
            ->editColumn('date', function(Forum $forum) {
                return $forum->date->format('dM');
            })
            ->editColumn('city', function (Forum $forum) {
                return $forum->city->getCity();
            })
            ->editColumn('location', function (Forum $forum) {
                return $forum->getLocation();
            })
            ->addColumn('actions', function ($forum) {
                $action = '';
                $action .= '<a title="Editar Foro" href="'.route('admin.forum.edit', $forum->id).'" class="btn btn-info-soft btn-sm mr-1"><i class="far fa-edit"></i></a>';
                $action .= '<a title="Asignar Role Play" href="'.route('admin.forum.create.roleplay', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="far fa-clipboard"></i></a>';
                $action .= '<a title="Asignar Entrevistas" href="'.route('admin.forum.create.interview', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="fas fa-pen-alt"></i></a>';
                $action .= '<a title="Asignar Aula TIC" href="'.route('admin.forum.create.aulatic', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="fas fa-bullhorn"></i></a>';
                $action .= '<a title="Asignar Work Shop" href="'.route('admin.forum.create.workshop', $forum->id).'" class="btn btn-inverse-soft btn-sm mr-1"><i class="fas fa-toolbox"></i></a>';
//                $action .= '<a href="#" onclick="deleteForum('.$forum->id.')" class="btn btn-danger-soft btn-sm "><i class="fas fa-trash"></i></a>';
                $action .= '<a href="#" class="btn btn-danger-soft btn-sm "><i class="fas fa-trash"></i></a>';
                if ($forum->status == true){
//                    $action .= '<a href="#" onclick="disableForum('.$forum->id.')" class="btn btn-danger-soft btn-sm "><i class="fas fa-ban"></i></a>';
                    $action .= '<a href="#" class="btn btn-danger-soft btn-sm "><i class="fas fa-ban"></i></a>';
                }else{
//                    $action .= '<a href="#" onclick="activeForum('.$forum->id.')" class="btn btn-success-soft btn-sm "><i class="fas fa-check-circle"></i></a>';
                    $action .= '<a href="#" class="btn btn-success-soft btn-sm "><i class="fas fa-check-circle"></i></a>';
                }
//                $action .= '<a href="#" onclick="deleteForum('.$forum->id.')" class="btn btn-danger-soft btn-sm "><i class="fas fa-trash"></i></a>';
                return $action;
            })
            ->rawColumns(['actions', 'city', 'location'])
            ->make(true);
    }

    public function destroy(Request $request)
    {
        $data = [];
        $data['success'] = false;

        $id = $request->id;
        $forum  = Forum::find($id);
        if (empty($forum)){
            $data['message'] = 'Error al eliminar este Foro';
            return $this->ReturnJson($data);
        }
        $forum->delete();

        $data['success'] = true;
        $data['message'] = 'Foro Eliminado';
        return $this->ReturnJson($data);
    }

    public function active(Request $request)
    {
        $data = [];
        $data['success'] = false;

        $id = $request->id;
        $forum  = Forum::find($id);
        if (empty($forum)){
            $data['message'] = 'Error al activar este Foro';
            return $this->ReturnJson($data);
        }
        $forum->status = 1;
        $forum->save();

        $data['success'] = true;
        $data['message'] = 'Foro Activado';
        return $this->ReturnJson($data);
    }

    public function disable(Request $request)
    {
        $data = [];
        $data['success'] = false;

        $id = $request->id;
        $forum  = Forum::find($id);
        if (empty($forum)){
            $data['message'] = 'Error al deshabilitar este Foro';
            return $this->ReturnJson($data);
        }
        $forum->status = 0;
        $forum->save();

        $data['success'] = true;
        $data['message'] = 'Foro deshabilitado';
        return $this->ReturnJson($data);
    }
}

resources/views/cpanel/forums/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="fs-17 font-weight-600 mb-0">Nuevo Foro</h6>
                        </div>
                        <div class="text-right">
                            <div class="actions">
                                <a href="{{route('admin.forums')}}" class="btn btn-inverse btn-sm">
                                    Atras
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body text-center">
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    @endif
                    <form action="{{route('admin.forum.store')}}" method="POST" id="forum-create" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                            <label for="date" class="col-sm-4 col-form-label font-weight-600">Fecha</label>
                            <div class="col-sm-6">
                                <input class="form-control" type="date" name="date" value="{{old('date')}}" min="{{Carbon::toDay()->toDateString()}}" id="date" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="city" class="col-sm-4 col-form-label font-weight-600">Ciudad</label>
                            <div class="col-sm-6">
                                <select name="city_id" id="city" class="select-search">
                                    @foreach($cities as $city)
                                        <option value="{{$city->id}}">{{$city->getCity()}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="location_es" class="col-sm-4 col-form-label font-weight-600">Ubicación ES</label>
                            <div class="col-sm-6">
                                <input class="form-control" type="text" name="location_es" value="{{old('location_es')}}" id="location_es" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="location_ca" class="col-sm-4 col-form-label font-weight-600">Ubicación VAL</label>
                            <div class="col-sm-6">
                                <input class="form-control" type="text" name="location_ca" value="{{old('location_ca')}}" id="location_ca" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="program_es" class="col-sm-4 col-form-label font-weight-600">Programa o Itinerario ES</label>
                            <div class="col-sm-6">
                                <input type="file" name="program_es" id="program_es" class="custom-input-file" data-multiple-caption="{count} files selected" />
                                <label for="program_es">
                                    <i class="fa fa-upload"></i>
                                    <span>Subir archivo…</span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group row">

                            <label for="program_ca" class="col-sm-4 col-form-label font-weight-600">Programa o Itinerario VAL</label>
                            <div class="col-sm-6">
                                <input type="file" name="program_ca" id="program_ca" class="custom-input-file" />
                                <label for="program_ca">
                                    <i class="fa fa-upload"></i>
                                    <span>Subir archivo…</span>
                                </label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cpanel/forums/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="fs-17 font-weight-600 mb-0">Forums</h6>
                        </div>
                        <div class="text-right">
                            <div class="actions">
                                <a href="{{route('admin.forum.create')}}" class="btn btn-success btn-sm">
                                    Nuevo
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="forum-list">
                            <thead>
                                <tr>
                                    <th>Fecha</th>
                                    <th>Ciudad</th>
                                    <th>Ubicación</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection
@push('js')
    <script type="text/javascript">
        var csrf_token = $('meta[name="csrf-token"]').attr('content');

        function deleteForum(id)
        {
            Swal.fire({
                title: 'Eliminar Foro',
                text: "¿Esta seguro de eliminar este Foro?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si',
                cancelButtonText: 'No'
            }).then((result) => {
                if (result.value) {
                    axios({
                        method: 'POST',
                        url: '/panel/forum/delete/' + id,
                        data: {_method: 'DELETE', _token: csrf_token}
                    }).then(function (response) {
                        if (response.data.success === true){
                            $("#forum-list").DataTable().ajax.reload();
                            Swal.fire({
                                position: 'top-end',
                                icon: 'success',
                                title: response.data.message,
                                showConfirmButton: false,
                                timer: 1500
                            });

                        }else{
                            $("#forum-list").DataTable().ajax.reload();
                            Swal.fire({
                                position: 'top-end',
                                icon: 'error',
                                title: response.data.message,
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }
                    });
                }
            })
        }
        function activeForum(id)
        {
            Swal.fire({
                title: 'HABILITAR',
                text: "Desea cambiar el Estatus a este Foro",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si',
                cancelButtonText: 'No'
            }).then((result) => {
                if (result.value) {
                    axios({
                        method: 'POST',
                        url: '{{route('admin.forum.status.active')}}?id=' + id,
                        data: {_method: 'PUT', _token: csrf_token}
                    }).then(function (response) {
                        if (response.data.success === true){
                            $("#forum-list").DataTable().ajax.reload();
                            Swal.fire({
                                position: 'top-end',
                                icon: 'success',
                                title: response.data.message,
                                showConfirmButton: false,
                                timer: 1500
                            });
                        }else{
                            $("#forum-list").DataTable().ajax.reload();
                            Swal.fire({
                                position: 'top-end',
                                icon: 'error',
                                title: response.data.message,
                                showConfirmButton: false,
                                timer: 1500
                            });
                        }
                    });
                }
            })
        }
        function disableForum(id)
        {
            Swal.fire({
                title: 'DESHABILITAR',
                text: "Desea cambiar el Estatus a este Foro",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si',
                cancelButtonText: 'No'
            }).then((result) => {
                if (result.value) {
                    axios({
                        method: 'POST',
                        url: '{{route('admin.forum.status.disable')}}?id=' + id,
                        data: {_method: 'PUT', _token: csrf_token}
                    }).then(function (response) {
                        console.log(response);
                        if (response.data.success === true){
                            Swal.fire({
                                position: 'top-end',
                                icon: 'success',
                                title: response.data.message,
                                showConfirmButton: false,
                                timer: 1500
                            });
                            $("#forum-list").DataTable().ajax.reload();
                        }else{
                            Swal.fire({
                                position: 'top-end',
                                icon: 'error',
                                title: response.data.message,
                                showConfirmButton: false,
                                timer: 1500
                            });
                            $("#forum-list").DataTable().ajax.reload();
                        }
                    });
                }
            })
        }

        $('#forum-list').DataTable({
            processing: true,
            serverSide: true,
            ajax:{
                url: "{{ route('admin.forums.data') }}"
            },
            order: [[ 4, "desc" ]],
            columns: [
                {
                    data:'date',
                    name:'date'
                },
                {
                    data:'city',
                    name:'city'
                },
                {
                    data:'location',
                    name:'location'
                },
                {
                    data:'actions',
                    name:'actions',
                    orderable: false
                },
                {data: 'created_at', 'visible': false, name: 'created_at'}

            ]
        });

    </script>
    @endpush