routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'panel', 'namespace' => 'Admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/users', 'AdminController@index')->name('users');
        Route::get('/users/create', 'AdminController@create')->name('user.create');
        Route::post('/users/store', 'AdminController@store')->name('user.store');
        Route::get('/users/edit/{id}', 'AdminController@edit')->name('user.edit');
        Route::put('/users/update/{id}', 'AdminController@update')->name('user.update');
        Route::delete('/users/delete/{id}', 'AdminController@destroy')->name('user.destroy');

        Route::get('companies', 'CompanyController@index')->name('companies');
        Route::get('companies/create', 'CompanyController@create')->name('company.create');
        Route::post('companies/store', 'CompanyController@store')->name('company.store');
        Route::get('companies/edit/{id}', 'CompanyController@edit')->name('company.edit');
        Route::put('companies/update/{id}', 'CompanyController@update')->name('company.update');
        Route::delete('companies/delete/{id}', 'CompanyController@destroy')->name('company.destroy');

        Route::get('/forums', 'ForumController@index')->name('forums');
        Route::get('/forum/create', 'ForumController@create')->name('forum.create');
        Route::post('/forum/store', 'ForumController@store')->name('forum.store');
        Route::get('/forum/edit/{id}', 'ForumController@edit')->name('forum.edit');
        Route::put('/forum/uptate/{id}', 'ForumController@update')->name('forum.update');
        Route::get('forum/{id}/role-playing', 'RolePlayController@indexRolePlay')->name('forum.create.roleplay');
        Route::post('forum/store/role-playing', 'RolePlayController@storeRolePlay')->name('forum.store.roleplay');
        Route::get('forum/role-play/edit/hour/{id}', 'RolePlayController@edit');
        Route::delete('forum/role-play/delete/hour/{id}', 'RolePlayController@destroy');
        Route::post('forum/role-play/hour/update', 'RolePlayController@update');
        Route::get('forum/{id}/interview', 'InterviewController@indexInterview')->name('forum.create.interview');
        Route::post('forum/store/interview', 'InterviewController@storeInterview')->name('forum.store.interview');
        Route::get('forum/interview/edit/hour/{id}', 'InterviewController@edit');
        Route::delete('forum/interview/delete/hour/{id}', 'InterviewController@destroy');
        Route::post('forum/interview/hour/update', 'InterviewController@update');
        Route::get('forum/{id}/aula-tic', 'AulaTicController@indexAulaTic')->name('forum.create.aulatic');
        Route::post('forum/store/aula-tic', 'AulaTicController@storeAulaTic')->name('forum.store.aulatic');
        Route::get('forum/aula-tic/edit/{id}', 'AulaTicController@edit')->name('forum.edit.aulatic');
        Route::put('forum/aula-tic/update/{id}', 'AulaTicController@update')->name('forum.update.aulatic');
        Route::delete('forum/aula-tic/delete/{id}', 'AulaTicController@destroy');
        Route::get('forum/{id}/work-shops', 'WorkShopController@indexWorkShop')->name('forum.create.workshop');
        Route::post('forum/store/work-shops', 'WorkShopController@storeWorkShop')->name('forum.store.workshop');
        Route::get('forum/competitors', 'CompetitorController@index')->name('forum.competitors');
        Route::get('forum/competitors/data', 'CompetitorController@data')->name('forum.competitors.data');
        Route::get('forum/data', 'ForumController@data')->name('forums.data');
        Route::get('forum/competitor/add', 'CompetitorController@create')->name('forum.competitor.create');
        Route::post('forum/competitor/store', 'CompetitorController@store')->name('forum.competitor.store');
        Route::put('forum/status/active/', 'ForumController@active')->name('forum.status.active');
        Route::put('forum/status/disable/', 'ForumController@disable')->name('forum.status.disable');
        Route::delete('forum/delete/{id}', 'ForumController@destroy')->name('forum.destroy');

        Route::get('/charts/ages', 'ChartController@chartAges');

        Route::prefix('cities')->group(function () {
            Route::get('/', 'CityController@index')->name('cities');
            Route::get('/create', 'CityController@create')->name('city.create');
            Route::post('/store', 'CityController@store')->name('city.store');
            Route::get('/edit/{id}', 'CityController@edit')->name('city.edit');
            Route::put('/update/{id}', 'CityController@update')->name('city.update');
            Route::delete('/delete/{id}', 'CityController@destroy')->name('city.update');
        });

        Route::prefix('hours')->group(function () {
            Route::get('/', 'HourController@index')->name('hours');
            Route::get('/create', 'HourController@create')->name('hour.create');
            Route::post('/store', 'HourController@store')->name('hour.store');
            Route::get('/edit/{id}', 'HourController@edit')->name('hour.edit');
            Route::put('/update/{id}', 'HourController@update')->name('hour.update');
        });

        Route::prefix('events')->group(function () {
            Route::name('events.')->group(function (){
                Route::prefix('role-plays')->group(function () {
                    Route::get('/', 'RolePlayController@index')->name('roleplays');
                    Route::get('/data', 'RolePlayController@data')->name('rolpelay.data');
                });
                Route::prefix('interviews')->group(function () {
                    Route::get('/', 'InterviewController@index')->name('interviews');
                    Route::get('/data', 'InterviewController@data')->name('interview.data');
                });
                Route::prefix('aula-tics')->group(function () {
                    Route::get('/', 'AulaTicController@index')->name('aulatics');
                    Route::get('/data', 'AulaTicController@data')->name('aulatic.data');
                });
                Route::prefix('work-shops')->group(function () {
                    Route::get('/', 'WorkShopController@index')->name('workshops');
                    Route::get('/data', 'WorkShopController@data')->name('workshop.data');
                });
            });
        });
    });
});



Route::get('/', 'WebController@index')->name('forum');
Route::post('/competitor/store', 'WebController@storeCompetitor')->name('store.competitor');
Route::prefix('events')->group(function () {
    Route::get('role-playing/{id?}', 'WebController@rolePlaying')->name('web.role-playing');
    Route::post('store/roleplay', 'WebController@storeRolePlaying')->name('web.store.roleplay');
    Route::get('entrevistas/{id?}', 'WebController@interview')->name('web.interview');
    Route::post('store/interview', 'WebController@storeInterview')->name('web.store.interview');
    Route::get('aula-tic/{id?}', 'WebController@aulatic')->name('web.aulatic');
    Route::post('store/aula-tic', 'WebController@storeAulaTic')->name('web.store.aulatic');
    Route::get('workshop/{id?}', 'WebController@workshop')->name('web.workshop');
    Route::post('store/work-shop', 'WebController@storeWorkshop')->name('web.store.workshop');
});

Route::get('get/hours/forum', 'WebController@getHoursByForum')->name('roleplay.get.hours.forum');
Route::get('get/company/interview', 'WebController@getCompanyByInterview')->name('interview.get.company.forum');
Route::get('get/hours/interview', 'WebController@getHoursByInterview')->name('interview.get.hours.forum');
Route::get('get/curses/aula-tic', 'WebController@getCursesByForum')->name('aulatic.get.curses.forum');
Route::get('get/workshops', 'WebController@getWorkShops')->name('forum.get.workshop');

Route::get('lang/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/RolePlay.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class RolePlay extends Model
{
    protected $guarded = [];

    // relations
    public function forum()
    {
        return $this->belongsTo(Forum::class);
    }
    public function RolePlayCompetitor()
    {
        return $this->hasMany(RolePlayCompetitor::class);
    }

    // getters
    public function getHourRolePlay()
    {
        $hour = Carbon::parse($this->hour);
        return $hour->format('H:i');
    }
}

app/Http/Controllers/Admin/RolePlayController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Forum;
use App\Hour;
use App\Http\Controllers\Controller;
use App\RolePlay;
use App\RolePlayCompetitor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Yajra\DataTables\Facades\DataTables;

class RolePlayController extends Controller
{
    public function index()
    {
        $pageTitle = 'Role Playing List';
        $pageIcon = 'fas fa-clipboard';
        $forums = Forum::all();
        $competitors = RolePlayCompetitor::all();

        return view('cpanel.roleplays.index', compact(
            'pageIcon', 'pageTitle', 'competitors', 'forums'
        ));
    }

    public function indexRolePlay($id)
    {
        $pageTitle = 'Role Play';
        $pageIcon = 'fas fa-clipboard';
        $forum = Forum::find($id);
        $roleplays = RolePlay::where('forum_id', $id)->get();
        $hours = Hour::all();
        return view('cpanel.forums.events.roleplay.index', compact(
            'pageTitle', 'pageIcon', 'forum', 'roleplays', 'hours'
        ));
    }

    public function storeRolePlay(Request $request)
    {
        $data = array();
        $find = array();
        foreach ($request->hour as $hour) {
            $find = RolePlay::where('hour', $hour)->where('forum_id', $request->forum_id)->first();
            if (empty($find)) {
                $data[] = RolePlay::create([
                    'forum_id' => $request->forum_id,
                    'hour' => $hour,
                    'places' => $request->places
                ]);
            }
        }
        if (!empty($find)) toastWarning('Hay Horas Duplicadas.');
        if (!empty($data)) toastSuccess('Horas Asignadas');
        return Redirect::back();
    }

    public function data(Request $request)
    {


        if ($request->forum != 'all') {
            $competitors = RolePlayCompetitor::where('forum_id', $request->forum)->get();
        } else {
            $competitors = RolePlayCompetitor::all();
        }

        return DataTables::of($competitors)
            ->editColumn('code', function (RolePlayCompetitor $competitor) {
                return $competitor->forum_competitor->code;
            })
            ->editColumn('first_name', function (RolePlayCompetitor $competitor) {
                return $competitor->forum_competitor->first_name;
            })
            ->editColumn('last_name', function (RolePlayCompetitor $competitor) {
                return $competitor->forum_competitor->last_name;
            })
            ->editColumn('dni', function (RolePlayCompetitor $competitor) {
                return $competitor->forum_competitor->dni;
            })
            ->editColumn('hour', function ($competitor) {
                return $competitor->roleplay->hour;
            })
            ->editColumn('forum', function ($competitor) {
                return $competitor->forum_competitor->forum->city->getCity();
            })
            ->rawColumns(['code', 'hour', 'forum'])
            ->make(true);

    }

    public function edit($id)
    {
        $where = array('id' => $id);
        $hour = RolePlay::where($where)->first();

        return response()->json($hour);
    }

    public function update(Request $request)
    {
        $hour =  RolePlay::updateOrCreate(
            ['id' => $request->roleplay_id],
            ['hour' => $request->hour, 'places' => $request->places]
        );

        return response()->json($hour);
    }

    public function destroy($id)
    {
        $data = [];
        $data['success'] = false;

        $id = array('id' => $id);
        if (empty($id))
        {
            $data['message']  = 'Error, intente nuevamente';
            return reponse()->json($data);
        }
        $hour = RolePlay::where($id)->delete();

        $data['success'] = true;
        $data['message'] = 'Hora Eliminada';

        return response()->json($data
        );
    }
}

resources/views/cpanel/forums/events/roleplay/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="fs-17 font-weight-600 mb-0">Horas del Role Playing</h6>
                        </div>
                        <div class="text-right">
                            <div class="actions">
                                <a href="{{route('admin.forums')}}" class="btn btn-inverse btn-sm">
                                    Atras
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body text-center">
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    @endif
                    <form action="{{route('admin.forum.store.roleplay')}}" method="POST">
                        @csrf
                        <div class="form-group row">
                            <label for="hour" class="col-sm-3 col-form-label font-weight-600">Horas</label>
                            <div class="col-sm-5">
                                <select name="hour[]" multiple id="hour" class="select-multiple" required>
                                    @foreach($hours as $hour)
                                        <option value="{{$hour->getHour()}}">{{$hour->getHour()}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="places" class="col-sm-3 col-form-label font-weight-600">Plazas</label>
                            <div class="col-sm-5">
                                <input type="number" name="places" id="places" class="form-control" value="{{old('places')}}" min="0" required>
                            </div>
                        </div>
                        <input type="hidden" name="forum_id" value="{{$forum->id}}">
                        <button type="submit" class="btn btn-success btn-sm">Agregar</button>
                    </form>
                </div>
            </div>
        </div>
        @includeIf('cpanel.forums.lists.forum_role_play', [$roleplays])
    </div>
    @include('layouts.modals.roleplay')
@endsection
@push('js')
    <script>

        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            /* When click edit user */
            $('body').on('click', '#edit-roleplay', function () {
                var hour = $(this).data('id');
                $.get('/panel/forum/role-play/edit/hour/' + hour +'/', function (data) {
                    console.log(data.hour);
                    $('#roleplayCrudModal').html("Editar Hora");
                    $('#btn-save').val("edit-roleplay");
                    $('#ajax-crud-modal').modal('show');
                    $('#roleplay_id').val(data.id);
                    $('#time').val(data.hour);
                    $('#plazas').val(data.places);
                })
            });
            //delete user login
            $('body').on('click', '#delete-roleplay', function () {
                const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 3000,
                    timerProgressBar: true,
                    onOpen: (toast) => {
                        toast.addEventListener('mouseenter', Swal.stopTimer);
                        toast.addEventListener('mouseleave', Swal.resumeTimer)
                    }
                });
                var hour_id = $(this).data("id");
                Swal.fire({
                    title: 'Eliminar Hora',
                    text: "¿Esta seguro de eliminar esta Hora?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Si',
                    cancelButtonText: 'No'
                }).then((result) => {
                    if (result.value) {
                        axios({
                            method: 'POST',
                            url: '/panel/forum/role-play/delete/hour/' + hour_id,
                            data: {_method: 'DELETE'}
                        }).then(function (response) {
                            if (response.data.success === true){
                                $("#roleplay_id_" + hour_id).remove();
                                Swal.fire({
                                    position: 'top-end',
                                    icon: 'success',
                                    title: response.data.message,
                                    showConfirmButton: false,
                                    timer: 1500
                                });

                            }else{
                                Swal.fire({
                                    position: 'top-end',
                                    icon: 'error',
                                    title: response.data.message,
                                    showConfirmButton: false,
                                    timer: 1500
                                })
                            }
                        });
                    }
                })
            });
        });

        if ($("#hourForm").length > 0) {
            $("#hourForm").validate({

                submitHandler: function(form) {

                    var actionType = $('#btn-save').val();
                    $('#btn-save').html('Actualizando..');

                    $.ajax({
                        data: $('#hourForm').serialize(),
                        url: "/panel/forum/role-play/hour/update",
                        type: "POST",
                        dataType: 'json',
                        success: function (data) {
                            console.log(data);
                            var hour = '<tr id="roleplay_id_' + data.id + '"><td>' + data.hour + '</td><td>' + data.places + '</td>';
                            hour += '<td><a href="javascript:void(0)" id="edit-roleplay" data-id="' + data.id + '" class="btn btn-info-soft btn-sm mr-2"><i class="fas fa-edit"></i></a>';
                            hour += '<a href="javascript:void(0)" id="delete-roleplay" data-id="' + data.id + '" class="btn btn-danger-soft btn-sm"><i class="fas fa-trash"></i></a></td></tr>';

                            $("#roleplay_id_" + data.id).replaceWith(hour);
                            $('#hourForm').trigger("reset");
                            $('#ajax-crud-modal').modal('hide');
                            $('#btn-save').html('Actualizar');
                            Toast.fire({
                                icon: 'success',
                                title: 'Hora actualizada'
                            })

                        },
                        error: function (data) {
                            console.log('Error:', data);
                            $('#btn-save').html('Actualizar');
                        }
                    });
                }
            })
        }

    </script>
    @endpush